### Lista de publicaciones
GET http://localhost:3000/api/publicaciones

### Ver publicacion por ID
GET http://localhost:3000/api/publicaciones/9ceacd54-76f9-11f0-8970-46de13098a39


### Ver comentarios de una publicacion
GET http://localhost:3000/api/publicaciones/a993b108-7677-11f0-8976-8e5e6c5471af/comentarios

### Crear un comentario (requiere token)
POST http://localhost:3000/api/publicaciones/a993b108-7677-11f0-8976-8e5e6c5471af/comentarios
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQzMWYzNjBlLTU2ZWQtNDcwYy1hNTNiLTQ3N2Y2OTAwNDU0YSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU0ODk3Mjk3LCJleHAiOjE3NTQ5NDA0OTd9.En6T_yMM4So7juCHutTw2pCsNoULfRVWo3zFc-4wxxA

{
    "contenido": "Pura pérdida con esto de la IA, no sirve para nada"
}

### Crear publicación (requiere token)
POST http://localhost:3000/api/publicaciones
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQzMWYzNjBlLTU2ZWQtNDcwYy1hNTNiLTQ3N2Y2OTAwNDU0YSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU0ODk3Mjk3LCJleHAiOjE3NTQ5NDA0OTd9.En6T_yMM4So7juCHutTw2pCsNoULfRVWo3zFc-4wxxA

{
    "titulo": "Estamos lanzando una nueva IA",
    "contenido": "Hoy lanzamos una nueva IA que promete revolucionar el mundo de la tecnología. ¡Mantente atento para más actualizaciones!"
}

### Editar publicación (solo el autor) 
PUT http://localhost:3000/api/publicaciones/6890628e-7266-11f0-b29f-2e22b3c7062a
Content-Type: application/json
Authorization: Bearer <token_jwt>

{
    "titulo": "Nuevo Título",
    "contenido": "Contenido modificado..."
}

### Eliminar publicación (solo el autor) 
DELETE http://localhost:3000/api/publicaciones/6890628e-7266-11f0-b29f-2e22b3c7062a
Authorization: Bearer <token_jwt>

### Registrar Usuario
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "nombre": "Caleb Ayala",
    "email": "calebayala777@gmail.com",
    "handle": "CalebAyala",
    "password": "palabraPase115",
    "role": "user"
}

### Iniciar sesión - Usuario
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "calebayala777@gmail.com",
    "password": "palabraPase115"
}


### Cambio de contraseña

PATCH http://localhost:3000/auth/set-password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjFiMDg0YWRiLTJkMjEtNGM1ZC04YTNlLTRjNWFkOTEyNDY2YSIsInBhc3N3b3JkIjoiJDJiJDEwJHA3YlFMZkd4a1QyWDdtN1FZRDFlWWU1S2VSRG5wSEhXb1c0czE2RDlFN0hkWDBDZVNjVWtTIiwiaWF0IjoxNzUyNzk0NjQzLCJleHAiOjE3NTI3OTgyNDN9.dC9JbCFBbyjW3hO_b5kc7GiHZH8MHWzo0vgNeWzKlm8

{ 
    "old_password":"palabraPase115",
    "new_password":"palabraPase#02311", 
    "confirm_password": "palabraPase#02311"
}